### ISSUE TITLE
migrate: IndexError: list index out of range

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#1043]
When running:

```sh
spinta migrate -p > migrate.sql
```

I get following error:

```python
Traceback (most recent call last):
  File "typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "spinta/cli/migrate.py", line 92, in migrate
    commands.migrate(context, manifest, migrate_meta)
  File "spinta/manifests/commands/migrate.py", line 30, in migrate
    commands.migrate(context, manifest, backend, migrate_meta)
  File "spinta/backends/postgresql/commands/migrate/migrate.py", line 91, in migrate
    commands.migrate(context, backend, meta, old, new)
  File "spinta/backends/postgresql/commands/migrate/model.py", line 54, in migrate
    zip_and_migrate_properties(
  File "spinta/backends/postgresql/helpers/migrate/migrate.py", line 980, in zip_and_migrate_properties
    handled = handle_internal_ref_to_scalar_conversion(
  File "spinta/backends/postgresql/helpers/migrate/migrate.py", line 452, in handle_internal_ref_to_scalar_conversion
    ref_primary_property = ref_model.flatprops[ref_primary_keys[0]]
IndexError: list index out of range
```

Local variables:

```python
ref_primary_keys = []
```

Looks like we get empty `ref_primary_keys` and we try to access `[0]` item.

Changes to manifest table:

- https://github.com/atviriduomenys/manifest/commit/6f748841ca0fddcc4d17dd8d9eaf261c2f9eebc0

**Comment by JustinasKen** [comment]
No longer can replicate this issue (might have been fixed with migration reworks).

But I see another problem.
I have tried to replicate this scenario localy and the script that got generated was:
| model | property | type | ref | level |
| ------- | --------- | ----- | --- | ----- |
| Test | | | id | |
| | id | integer | | |
| | code | string | | |
| | | | | |
| New | | | id | |
| | id | integer | | |
| | test | ref | Test[code] | 4 |


```sql
BEGIN;

ALTER TABLE "example/New" ADD COLUMN test TEXT;

UPDATE "example/New" SET test="example/Test".id FROM "example/Test" WHERE "example/New"."test._id" = "example/Test"._id;

ALTER TABLE "example/New" RENAME "test._id" TO "__test._id";

DROP INDEX "ix_example/New_test._id";

ALTER TABLE "example/New" DROP CONSTRAINT "fk_example/New_test._id";

COMMIT;
```
In this scenario, `model` `Test`, has primary key `id`
`model` `
when initialy I had `ref` with `Test[code]`
