### ISSUE TITLE
Push ref dependencies

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#149]
Models with self-references can't be simply pushed by reading whole model data, self references must be automatically parametrized and read in chunk, starting with least dependent objects first.

For example if we have data like this:

| id | parent |
| -- | ------ |
| 1  | null   |
| 2  | 1      | 

Here, we should start with a block, where parent is null, once that done, then we should read all rows, where parent is 1. And so on. This way, we can ensure, that objects are created in correct order and we will not get foreign key constraints.

There might be more complicated cases, like cycles, but I will deal with such cases later.

### Depends on

- #311 
- https://github.com/atviriduomenys/spinta/issues/363

**Comment by sirex** [comment]
Similar issue:

```python
ERROR: Error when sending and receiving data. Model datasets/gov/ivpk/adp/catalog/Dataset,
Server response (status=500):
    {
        'errors': [
            {
                'code': 'IntegrityError',
                'message': '''
                    (psycopg2.errors.ForeignKeyViolation) insert or update on table
                    "datasets/gov/ivpk/adp/catalog/UserLike" violates foreign key constraint
                    "fk_datasets/gov/ivpk/adp/catalog/UserLike_request._id"
                    
                    DETAIL:
                      Key (request._id)=(1a0d39cf-31f9-47d3-8691-761ff9e4814e) is not present in
                      table "datasets/gov/ivpk/adp/catalog/Request".
                    
                    SQL:
                      INSERT INTO "datasets/gov/ivpk/adp/catalog/UserLike":
                        _txn: 'c66bb4ad-b884-4a6b-b86b-eb92a8b64751',
                        _created: TIMEZONE('utc', CURRENT_TIMESTAMP),
                        _id: '152cc978-1f48-4271-ab57-fe3c1ab14327',
                        _revision: 'ee9262cc-f4f6-4b87-9cd8-fb748ddcfc8e',
                        id: 13,
                        created: '2021-03-01T08:52:48.356114',
                        modified: NULL,
                        version: 0,
                        request._id: '1a0d39cf-31f9-47d3-8691-761ff9e4814e'
                ''',
            },
        ],
    }
ERROR: Error while reading data.
Traceback (most recent call last):
  File "spinta/cli/push.py", line 200, in push
    next(rows)
  File "spinta/cli/push.py", line 468, in _save_push_state
    for row in rows:
  File "spinta/cli/push.py", line 268, in _push_to_remote_spinta
    yield from _send_and_receive(
  File "spinta/cli/push.py", line 325, in _send_and_receive
    yield from _map_sent_and_recv(rows, recv)
  File "spinta/cli/push.py", line 388, in _map_sent_and_recv
    assert len(sent) == len(recv), (
TypeError: object of type 'NoneType' has no len()
```

**Comment by JuliusLADP** [comment]
lentelė priklauso pati nuo savęs - tokio atvejo rašymo eiliškumo sutvarkymas. Klaida jeigu pirmiau rašo vaiką, kai dar nėra tėvo

**Comment by Grigorjeva11** [comment]
Prašau patikslinti, ar dar aktualu. Jeigu aktualu, pažymėkite prioritetą (P0 - aukščiausias).

**Comment by Grigorjeva11** [comment]
Reikalingas platesnis aptarimas.

**Comment by SauliusPetraitis** [comment]
@sirex - jei turi ideju kaip be memory padaryt - padarom. O galo variantas nenumušti brandos lygio kai kalba eina apie self reference.
