### ISSUE TITLE
TypeError when deleting/patching a row with geometry

### ISSUE THREAD

**Issue by julijonas** [atviriduomenys/spinta#418]
It seems that delete fails with `TypeError: argument of type 'NotAvailable' is not iterable` when the row has geometry set.

```
$ curl -XPOST https://put-test.data.gov.lt/datasets/a/b/c/d -d '{"koord":"POINT (1 1)"}' -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN"
{"_type":"datasets/a/b/c/d","_id":"89da748e-5f9c-4f81-af24-ee174aa1b718",...,"koord":"POINT (1 1)"}

$ curl -XDELETE https://put-test.data.gov.lt/datasets/a/b/c/d/89da748e-5f9c-4f81-af24-ee174aa1b718 -H "Authorization: Bearer $TOKEN"   
{"errors":[{"code":"TypeError","message":"argument of type 'NotAvailable' is not iterable"}]}
```

The same error happens when you're patching a row that has geometry set but you don't specify geometry value again (as you only want to specify changed fields).

```
$ curl -XPATCH https://put-test.data.gov.lt/datasets/a/b/c/d/89da748e-5f9c-4f81-af24-ee174aa1b718 -d '{"date":"2000-01-01","_revision":"b4d80faf-c168-45d7-8ac3-5c6e53cf86b9"}' -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN"
{"errors":[{"code":"TypeError","message":"argument of type 'NotAvailable' is not iterable"}]}
```

**Comment by sirex** [comment]
Traceback from logs:

```python
Traceback (most recent call last):
  File "spinta/api.py", line 94, in homepage
    return await create_http_response(context, params, request)
  File "spinta/utils/response.py", line 201, in create_http_response
    return await commands.push(
  File "spinta/commands/write.py", line 96, in push
    status_code, response = await _batch_response(
  File "spinta/commands/write.py", line 1132, in _batch_response
    async for data in results:
  File "spinta/accesslog/__init__.py", line 174, in log_async_response
    async for row in rows:
  File "spinta/commands/write.py", line 187, in push_stream
    async for data in dstream:
  File "spinta/backends/postgresql/commands/changes.py", line 25, in create_changelog_entry
    async for data in dstream:
  File "spinta/backends/postgresql/commands/write.py", line 92, in delete
    commands.before_write(context, model, backend, data=data)
  File "spinta/backends/postgresql/commands/write.py", line 118, in before_write
    value = commands.before_write(
  File "spinta/backends/postgresql/types/geometry/write.py", line 14, in before_write
    if 'SRID' not in data.patch and dtype.srid is not None:
TypeError: argument of type 'NotAvailable' is not iterable
ERROR: Error: argument of type 'NotAvailable' is not iterable
```
