### ISSUE TITLE
Error when export data in CSV

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#528]
After upgrade, I get multiple errors like these:

```python
Traceback (most recent call last):
  File "spinta/utils/response.py", line 246, in aiter
    for data in stream:
  File "spinta/formats/csv/commands.py", line 60, in _render_csv
    writer.writerow(row)
  File "csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'sav_kodas', 'pmprs_v', 'pmprs_pk', 'pmprs_iv', 'sav_kodas_regist'
```

- https://get.data.gov.lt/datasets/gov/hi/mirtys/NuolatinisGyventojas
- https://github.com/atviriduomenys/manifest/blob/master/datasets/gov/hi/mirties_priezastys.csv

```
ValueError: dict contains fields not in fieldnames: 'org_savivaldybe'
```

- https://get.data.gov.lt/datasets/gov/rc/espbiis/receptai/Receptas
- https://github.com/atviriduomenys/manifest/blob/master/datasets/gov/rc/espbiis/receptai.csv

```
ValueError: dict contains fields not in fieldnames: 'work_group', 'notification_status'
```

- https://get.data.gov.lt/datasets/gov/lst/standards/Project
- https://github.com/atviriduomenys/manifest/blob/master/datasets/gov/lst/standards.csv

My guess, error happens, when value of a `ref` property is `None`.

**Comment by sirex** [comment]
Not sure if this is related, but I also get following errors:

```python
Traceback (most recent call last):
  File "spinta/formats/rdf/commands.py", line 230, in _stream
    for row in data:
  File "spinta/commands/read.py", line 130, in <genexpr>
    commands.prepare_data_for_response(
  File "spinta/formats/rdf/commands.py", line 271, in prepare_data_for_response
    elem = commands.prepare_dtype_for_response(
  File "spinta/formats/rdf/commands.py", line 416, in prepare_dtype_for_response
    if len(data_dict) == 1 and '_id' in data_dict or '_uri' in data_dict:
TypeError: object of type 'NoneType' has no len()
```
