### ISSUE TITLE
AttributeError on starting Spinta

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#590]
When starting Spinta server `spinta run`, sometimes following error is raised:

```python
Traceback (most recent call last):
  File "spinta/asgi.py", line 18, in <module>
    commands.check(context, config)
  File "multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "spinta/types/config.py", line 109, in check
    if config.default_auth_client and not client_name_exists(path, config.default_auth_client):
  File "spinta/auth.py", line 586, in client_name_exists
    if client in keymap.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

After starting it again, error usually disappears.

It looks, that `config/clients/helpers/keymap.yml` becomes empty at the time when `client_name_exists` function is called. Maybe there is some raise condition is involved here.

**Comment by sirex** [comment]
Galimai susijusi klaida.

```python
Traceback (most recent call last):
  File "gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "spinta/asgi.py", line 17, in <module>
    commands.load(context, config)
  File "multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "spinta/types/config.py", line 105, in load
    handle_auth_client_files(config)
  File "spinta/auth.py", line 781, in handle_auth_client_files
    migrate_old_client_file(path, item)
  File "spinta/auth.py", line 726, in migrate_old_client_file
    old_data["client_name"] = old_data["client_id"]
TypeError: list indices must be integers or slices, not str
```

Klaida galimai pasireiškia todėl, kad yra klaidingai sukurtas `clients` YAML failas, kuriame yra pateiktas tik scope sąrašas:

```
- spinta_getall
- spinta_getone
...
```

Jei yra toks sugadintas failas, tada gaunamas klaida, kad tikisi dict, o gauna list.

Reikėtu pataisyti, kad skaitant client duomenis, patikrintu ar jis yra dict, jei ne, tada nurodytų koks failas ir kad jo nepavyko nuskaityti.

**Comment by JustinasKen** [comment]
#556 užduotis sutvarkė pradinę problemą, jei vis dar reikia:

> Reikėtu pataisyti, kad skaitant client duomenis, patikrintu ar jis yra dict, jei ne, tada nurodytų koks failas ir kad jo nepavyko nuskaityti.

Reiktu tam atskiros užduoties

**Comment by JuliusLADP** [comment]
Suformuokite užduotį: "pataisyti, kad skaitant client duomenis, patikrintu ar jis yra dict, jei ne, tada nurodytų koks failas ir kad jo nepavyko nuskaityti"

**Comment by Grigorjeva11** [comment]
Sukurtas #933
