### ISSUE TITLE
Missing SQL `NULLS LAST` support

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#723]
When running `spinta push` on 0.1.66 Spinta version, following error is thrown:

```python
Traceback (most recent call last):
  File "spinta/cli/helpers/push/write.py", line 360, in _push_rows
    next(rows)
  File "spinta/cli/helpers/push/state.py", line 142, in save_push_state
    for row in rows:
  File "spinta/cli/helpers/push/write.py", line 223, in _push_to_remote_spinta
    for row in rows:
  File "spinta/cli/helpers/push/write.py", line 36, in _prepare_rows_for_push
    for row in rows:
  File "spinta/cli/helpers/push/state.py", line 95, in check_push_state
    for model_type, group in itertools.groupby(rows, key=_get_model_type):
  File "spinta/cli/helpers/push/read.py", line 136, in read_rows
    yield from _get_model_rows(
  File "spinta/cli/helpers/push/read.py", line 116, in _get_model_rows
    for row in rows:
  File "spinta/cli/helpers/push/read.py", line 61, in _iter_model_rows
    for row in rows:
  File "spinta/cli/helpers/push/read.py", line 254, in _read_rows_by_pages
    state_row = next(state_rows, None)
  File "spinta/cli/helpers/push/read.py", line 383, in _get_state_rows_with_page
    rows = conn.execute(
  File "sqlalchemy/engine/base.py", line 1263, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
  File "sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError:
    (sqlite3.OperationalError) near "NULLS": syntax error
```

SQL:

```sql
SELECT
    id,
    checksum,
    revision,
    pushed,
    error,
    data,
    "page.id"
FROM "datasets/gov/example/City"
ORDER BY "page.id" ASC NULLS LAST
LIMIT 1001
OFFSET 0
```

It looks, that SQLite does not support `NULLS LAST`.

`NULLS LAST` was added since [SQLite 3.30.0 (2019-10-04) version](https://www.sqlite.org/changes.html#version_3_30_0).

Probably better option, to not use `NULLS LAST` to avoid incompatibility issues.

### Related

- https://github.com/atviriduomenys/spinta/issues/366#issuecomment-1976627947
- https://github.com/atviriduomenys/spinta/issues/411

**Comment by sirex** [comment]
Users report following SQLite versions:

```
$ sqlite3 --version
3.7.17 2013-05-20
```

**Comment by sirex** [comment]
Possible solution is to use [sclean](https://pypi.org/project/sqlean.py/), which brings newer SQLite version bundled with the package:

https://github.com/atviriduomenys/spinta/blob/4c493ecb5aebc29a707418d372ab15ea5359aceb/spinta/utils/sqlalchemy.py#L10-L15

This was already done for keymaps.

**Comment by JuliusLADP** [comment]
Mantai, jeigu negali operatyviai pratestuoti, tai tuomet permesk į Diegimas
