### ISSUE TITLE
Del erroru spintoj 

### ISSUE THREAD

**Issue by IngaIVPK** [atviriduomenys/spinta#805]
Pridedu susirašinėjimą, atsakyti reikėtų VVPT

________________________________________________________________________________________________________________________________

Išsiųsta: 2024 m. rugsėjo 18 d., trečiadienis 15:31

Sveiki, esu naujai prisijungęs prie VPT, ir yra poreikis atnaujinti atvirus duomenis.
Gal galim prisiminti situaciją ir pratęsti naujinimą? Kaip suprantu jūsų pusėje buvo klaidų/problemų, tai gal jau išsisprendė?

____________________________________________________________________________________________________________________________________

Sent: Thursday, May 9, 2024 15:47

 
neranda poetry jokio, nezinau is kur ji leist

![image](https://github.com/user-attachments/assets/eaf75c79-e381-465c-98d4-eaec7d73
f8be)

_____________________________________________________________________________________________________________________________

Sent: Thursday, May 9, 2024 3:43 PM

Sveiki,
ar po atsinaujinimo atlikot poetry atnaujinimus, tai yra naudojo poetry update komandą?

_____________________________________________________________________________________________________________________________

Sent: Thursday, May 9, 2024 2:33 PM

cia dar is new duomenu
 
$ less /opt/spinta/var/logs/push/new.log
Loading InlineManifest manifest default
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 646, in pymssql._pymssql.connect
  File "src/pymssql/_mssql.pyx", line 2106, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 698, in pymssql._mssql.MSSQLConnection.__init__
  File "src/pymssql/_mssql.pyx", line 1815, in pymssql._mssql.maybe_raise_MSSQLDatabaseException
  File "src/pymssql/_mssql.pyx", line 1832, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (20017, b'DB-Lib error message 20017, severity 9:\nUnexpected EOF from the server (10.254.254.10)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (10.254.254.10)\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (10.254.254.10)\n')
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 610, in __connect
    with util.safe_reraise():
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/spinta/env/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)

**Comment by JuliusLADP** [comment]
Laukiu Justino komentaro dėl situacijos?

**Comment by JustinasKen** [comment]
Susirašiau su žmogumi, kuriam ši klaida įvyko. Gavau informaciją, kokias versijas naudoja. Pastebėjau, kad naudoja 2005 metų mssql serverį, kuris jau kaip supratau nuo 2016 visiškai nebepalaikomas. Tai bandysiu lokaliai pasileisti pas save ir pažiūrėti ar pavyksta atkartoti klaidą.

**Comment by JustinasKen** [comment]
Nepavyksta pasileisti lokaliai 2005 mssql serverį, kadangi per daug sena versija. Iš klaidos galima daryti keleta spėjimų:

- Blogai manifeste nurodytas prisijungimo `connection` `dsn`. Kadangi rašo, jog negali prisijungti prie duomenų bazės serverio.
- Gali būti, kad naujesnės bibliotekų versijos (`pymssql`) atėjo su driveriais, kurie nepalaiko senų versijų, bet apie tai nieko neradau dokumentacijoje.

**Comment by JustinasKen** [comment]
Pabandžiau pasileisti 2017 versiją lokaliai. Viskas veikė gerai, bet pamačiau pastebėjimą, kad rašant `connection` string ir nurodant slaptažodį, jei jis turi specialius ženklus, kaip `@`, reikia juos užkoduotis, kitu atvėju gavau panašią klaidą.

Pavyzdžiui slaptažodis: `Passw@rd` turi būti užkoduotas į `Passw%40rd`.
Plačiau apie koduotes:
https://www.w3schools.com/tags/ref_urlencode.ASP

**Comment by JuliusLADP** [comment]
Paaiškinti paklausėjui, jeigu to dar nebuvo padaryta ir uždaryti užduotį.

**Comment by IngaIVPK** [comment]
Justinai, rašote, kad susirašėte su užklausą pateikusiu žmogumu, norime pasiklausti, ar jam atsakėte tai, ką surašėte čia? 

Ačiū.
