### ISSUE TITLE
DSA error: Enum '' item 'None' with the same value is already defined (AR)

### ISSUE THREAD

**Issue by ievabraskute** [atviriduomenys/spinta#978]
❗ see comments

kai komanda `spinta check pavyzdys_978.xlsx` leidžiama su žemiau nurodytu inputu (galimos `enum` reikšmės nurodytos `prepare` stukpelyje), gaunama klaida (žr. pridedamą traceback)

Pradiniai duomenys:

```
id | d | r | b | m | property   | type    | ref | source     | prepare | level | access | uri | title | description
   | test_dataset               |         |     |            |         |       |        |     |       |
   |   | resource1              | xml     |     |            |         |       |        |     |       |
   |                            |         |     |            |         |       |        |     |       |
   |   |   |   | Area           |         |     |            |         |       |        |     |       |
   |   |   |   |   | name       | string  |     |            |         |       |        |     |       |
   |                            |         |     |            |         |       |        |     |       |
   |   |   |   | Country        |         |     | Country    |         |       |        |     |       |
   |   |   |   |   | name       | string  |     | name       |         |       |        |     |       |
   |   |   |   |   | code       | string  |     | code       |         |       |        |     |       |
   |   |   |   |   | population | integer |     | population |         |       |        |     |       |
   |   |   |   |   | driving    | string  |     |            |         |       | open   |     |       |
   |                            | enum    |     |            | "left"  | 0     | open   |     |       |
   |                            |         |     |            | "right" | 0     | open   |     |       |
```
[pavyzdys_978.xlsx](https://github.com/user-attachments/files/18561486/pavyzdys_978.xlsx)

Pageidaujamas rezultatas:
`Ok`

Gaunamas rezultatas:

klaida:

```python
Traceback (most recent call last):
  File "spinta/cli/config.py", line 38, in check
    prepare_manifest(context, ensure_config_dir=True, full_load=True)
  File "spinta/cli/helpers/store.py", line 147, in prepare_manifest
    store = load_manifest(
  File "spinta/cli/helpers/store.py", line 129, in load_manifest
    commands.load(
  File "spinta/manifests/yaml/commands/load.py", line 110, in load
    commands.load(
  File "spinta/manifests/tabular/commands/load.py", line 59, in load
    load_manifest_nodes(context, into, schemas, source=manifest)
  File "spinta/manifests/helpers.py", line 133, in load_manifest_nodes
    for eid, schema in schemas:
  File "spinta/manifests/tabular/helpers.py", line 1801, in read_tabular_manifest
    yield from _read_tabular_manifest_rows(
  File "spinta/manifests/tabular/helpers.py", line 1758, in _read_tabular_manifest_rows
    yield from state.release()
  File "spinta/manifests/tabular/helpers.py", line 1718, in release
    parent.leave()
  File "spinta/manifests/tabular/helpers.py", line 1276, in leave
    self.state.stack[-1].append(self.data)
  File "spinta/manifests/tabular/helpers.py", line 1516, in append
    self.read(row)
  File "spinta/manifests/tabular/helpers.py", line 1509, in read
    self.error(
  File "spinta/manifests/tabular/helpers.py", line 242, in error
    raise TabularManifestError(f"{self.path}:{self.line}: {message}")
spinta.manifests.tabular.helpers.TabularManifestError:
    xsds/tikrinimui/pavyzdys_978.xlsx:Sheet1:13:
        Enum '' item 'None' with the same value is already defined.
```

## Solution

Pagal dokumentacijos 1.0 versiją (kurią nurodėte), stulpelis prepare skirtas reikšmėms modifikuoti, transformuoti arba standartizuoti prieš jas įrašant į paskirties struktūrą. Taigi:

Jei enum reikšmės pakeičiamos arba transformuojamos į kitas reikšmes, jos turėtų būti aprašytos prepare.
Jei reikšmės tiesiogiai perkeliamas iš šaltinio, jos turėtų būti source stulpelyje.

Problema kad patikrinimas ar source tuščias buvo klaidingas ir tikrindavo None reikšmę tik po konvertavimo į string, kas pasekoje pakeisdavo reikšmę iš None i "None". Sprendimas - konvertuoti į String po patikrinimo - https://github.com/atviriduomenys/spinta/pull/1115

Papildomai konvertuojant None i empty string ("") turi išspręsti tokias problemas iš anksčiau - https://github.com/atviriduomenys/spinta/pull/1115/files#diff-ef698dfa7530dce56bc8139a272f35940c59a01449c3c23bfe5fbb538effe5ccR1868

Su tokiu sprendimu visi testai praeina (kurie praeina ir master šakoje)

## Testavimas

Testuojant reikėtu patikrinti scenarijus aprašytus čia:

- https://github.com/ivpk/dsa/issues/46

Taip pat reikėtu išbandyti tiek su CSV, tiek su XLSX DSA formatais.

## Susiję

- https://github.com/ivpk/dsa/issues/46
- https://github.com/atviriduomenys/spinta/issues/1146

**Comment by karina-klinkeviciute** [comment]
This is because they added `enum` values to the `prepare` not `source` column

**Comment by karina-klinkeviciute** [comment]
No, they are correctly defined in the `prepare` column. The question is - should they also have a `source` in this case, or not. It is possible to not have a `source` if model doesn't have a `resource`. I'm not sure if this empty `source` is correct in this case, or not.

Manto komentaras:
Teoriškai reikėtu perkelti už resource, bet techniškai nėra būtina. RC tokiu būdu formuoja koncepcinį modelį, kuris nėra susietas so jokiu resource ir naudoja tokius modelius, kaip bazinius.
 
Konkrečiai LocatorDesignator/:part atveju, modelis naudojamas kaip jungtinio modelio dalis /:part. Kuris tiesiogiai nesiejamas su šaltiniu ir yra naudojamas ir siejamas su šaltiniu jungtiniame modelyje.
 
Taip, kaip dabar apibrėžtas LocatorDesignator/:part/type yra padaryta gerai.

**Comment by karina-klinkeviciute** [comment]
I can't reproduce this error

**Comment by sirex** [comment]
> I can't reproduce this error

Did you checked https://github.com/ivpk/metadata/pulls? Where this error comes from and did you tried to reproduce this on the same pull request?

**Comment by karina-klinkeviciute** [comment]
no, I haven't tried to reproduce it with pulls. I will though. I suspect it might be on #1004

**Comment by karina-klinkeviciute** [comment]
I tried with the pull request, on which @ievabraskute was registering the errors (branch #582) but even with that branch I can't reproduce the error. 

@ievabraskute can you reproduce this again?

**Comment by varzgalys** [comment]
Any input file?

**Comment by karina-klinkeviciute** [comment]
Prieš tai komentaruose rašiau, kad man nepavyko reproducinti, bet pasitikrinau - pas mane failas buvo pakoreguotas, ir enum items perkelta į source stulpelį. 

Dabar sukūriau pavyzdį reproducinimui: 

[pavyzdys_978.xlsx](https://github.com/user-attachments/files/18561486/pavyzdys_978.xlsx)

Jame irgi gaunu tą pačią klaidą.

Kai reikšmės nurodytos `prepare`, o ne `source` stulpelyje (kai kuriais atvejais tai galima), metama ši klaida.

**Comment by varzgalys** [comment]
Pagal dokumentacijos 1.0 versiją (kurią nurodėte), stulpelis prepare skirtas reikšmėms modifikuoti, transformuoti arba standartizuoti prieš jas įrašant į paskirties struktūrą. Taigi:

Jei enum reikšmės pakeičiamos arba transformuojamos į kitas reikšmes, jos turėtų būti aprašytos prepare.
Jei reikšmės tiesiogiai perkeliamas iš šaltinio, jos turėtų būti source stulpelyje.

Problema kad patikrinimas ar source tuščias buvo klaidingas ir tikrindavo None reikšmę tik po konvertavimo į string, kas pasekoje pakeisdavo reikšmę iš None i "None". Sprendimas - konvertuoti į String po patikrinimo - https://github.com/atviriduomenys/spinta/pull/1115

**Comment by varzgalys** [comment]
> Tikriausiai geras sprendimas. Čia turiu įtarimą, kad klaida atsiranda tik XLSX atveju, nes CSV, jei neklystu visada būna `str` tipas, bet XLSX atveju, tuščios celės gali būti `""` arba `None`.
> 
> Tai matyt tokio apdorojimo pakanka.
> 
> Siūlau pagalvoti dar vienu žingsniu į priekį:
> 
> [spinta/spinta/manifests/tabular/helpers.py](https://github.com/atviriduomenys/spinta/blob/3d1bfee2d00bb7d0fa1d02769bde75e87f7e137f/spinta/manifests/tabular/helpers.py#L1852-L1875)
> 
> Lines 1852 to 1875 in [3d1bfee](/atviriduomenys/spinta/commit/3d1bfee2d00bb7d0fa1d02769bde75e87f7e137f)
> 
>  def _read_xlsx_manifest(path: str) -> Iterator[Tuple[str, List[str]]]: 
>      wb = openpyxl.load_workbook(path) 
>   
>      yield '1', DATASET 
>   
>      for sheet in wb: 
>          rows = sheet.iter_rows(values_only=True) 
>          cols = next(rows, None) 
>          if cols is None: 
>              continue 
>          cols = normalizes_columns(cols) 
>          cols = [cols.index(c) if c in cols else None for c in DATASET] 
>   
>          empty_rows = _empty_rows_counter() 
>          for i, row in enumerate(rows, 2): 
>              row = [row[c] if c is not None else None for c in cols] 
>              yield f'{sheet.title}:{i}', row 
>   
>              if empty_rows(row) > 100: 
>                  log.warning( 
>                      f"Too many consequent empty rows, stop reading {path} " 
>                      f"at {i} row." 
>                  ) 
>                  break 
> Dabar XLSX atveju, ne tik `prepare`, bet ir kiti stulpeliai gali grąžinti `None`. Dauguma testų yra atliekami su CSV ir ASCII, kuri nėra `None`, todėl, gal verta iš karto `None` panaikinti XLSX skaitymo metu?
> 
> Tik reikia patikrinti, kiek toks pataisymas sulaužytu testų.

Convertuojant None i empty string ("") turi išspręsti tokias problemas iš anksčiau - https://github.com/atviriduomenys/spinta/pull/1115/files#diff-ef698dfa7530dce56bc8139a272f35940c59a01449c3c23bfe5fbb538effe5ccR1868

Su tokiu sprendimu visi testai praeina (kurie praeina ir master šakoje)

**Comment by sirex** [comment]
Aprašymas neatitinka

https://spinta.readthedocs.io/en/latest/contrib/issues.html#task-description

Reikia pateikti klaidos minimalų atkartojamą pavyzdį ir užduoties aprašyme nurodyti, įvesties, išvesties failus ir klaidos traceback.

**Comment by karina-klinkeviciute** [comment]
atnaujinau užduoties aprašymą

**Comment by sirex** [comment]
Teoriškai, viskas gerai, testuojant reikėtu patikrinti scenarijus aprašytus čia:

- https://github.com/ivpk/dsa/issues/46

Taip pat reikėtu išbandyti tiek su CSV, tiek su XLSX DSA formatais.

**Comment by riteris13** [comment]
# Priėmimo testavimo scenarijus

## Testuojamas funkcionalumas
`enum` reikšmių sukeitimas kai jos pateikiamos tuščiomis eilutėmis, be Spintos klaidos
### Testavimo eiga
 1. Pateikiamas DSA, kuriame yra `enum` su tuščiomis vertėmis, Spinta negeneruoja klaidos

 
### Testuojama kaip:
DSA tikrinantis partnerio atstovas

  
## Testavimas
 
 1. Pateikiamas DSA, kuriame yra `enum` su tuščiomis vertėmis, Spinta negeneruoja klaidos
    
  #### Sąlygos
  1. Paruoštas pavyzdinis DSA dokumentas, pagal užduoties aprašyme pateiktą šiuo metu klaidą generuojančią struktūrą
  #### Veiksmai
  1. Naudotojas komandinėje eilutėje iškviečia "Spinta check *dsa dokumentas* "
  2. Spinta negrąžina jokios klaidos
  
  #### Rezultatas
  1. `Spinta check` įvyksta be klaidos

**Comment by karina-klinkeviciute** [comment]
Testavimo aprašymo scenarijus šiek tiek netikslus. 

> enum reikšmių sukeitimas kai jos pateikiamos tuščiomis eilutėmis, be Spintos klaidos 
Ką reiškia "reikšmių sukeitimas"?

Ne `enum` eilutė turėtų būti tuščia, bet `source` stulpelis `enum` eilutėje turėtų tuščias, tačiau `prepare` stulpelyje turėtų būti reikšmė, ir ši reikšmė turėtų būti arba tekstas kabutėse, arba `noop()` funkcija.

**Comment by riteris13** [comment]
Testavimo scenarijus patikslintas pagal pateiktą komentarą.
