### ISSUE TITLE
Spinta doesn't register items in the resource params section

### ISSUE THREAD

**Issue by karina-klinkeviciute** [atviriduomenys/spinta#979]
![Image](https://github.com/user-attachments/assets/cd80d4f8-dbc5-4f62-b447-fd0a01e746cb)
Jei yra daugiau nei vienas parametras `resource` dalyje, leidžiant `spinta copy` metama klaida.

Pradiniai duomenys: 

DSA aprašas: 

[pavyzdys_979.xlsx](https://github.com/user-attachments/files/18563334/pavyzdys_979.xlsx) - XLSX failas, 

aprašas ASCII formatu:

```
d | r | b | m | property  | type    | ref    | source      | prepare
test_dataset              |         |        |             |
  | resource1             | xml     |        |             |
                          | param   | param1 | param1      | body()
                          |         | param2 | param2      | body()
                          |         | param3 | param3      | body()
                          |         |        |             |
  |   |   | Continent     |         |        |             |
  |   |   |   | name      | string  |        | name/text() |
  |   |   |   | id        | integer |        | name/text() |

```

Laukiamas rezultatas:
paleidus `spinta copy pavyzdys_979.xlsx` atvaizduojamas DSA aprašas, identiškas aukščiau pateiktam DSA aprašui ASCII formatu. 

Klaidos traceback:

```python
Traceback (most recent call last):
  File "spinta/cli/config.py", line 38, in check
    prepare_manifest(context, ensure_config_dir=True, full_load=True)
  File "spinta/cli/helpers/store.py", line 147, in prepare_manifest
    store = load_manifest(
  File "spinta/cli/helpers/store.py", line 129, in load_manifest
    commands.load(
  File "spinta/manifests/yaml/commands/load.py", line 110, in load
    commands.load(
  File "spinta/manifests/tabular/commands/load.py", line 59, in load
    load_manifest_nodes(context, into, schemas, source=manifest)
  File "spinta/manifests/helpers.py", line 133, in load_manifest_nodes
    for eid, schema in schemas:
  File "spinta/manifests/tabular/helpers.py", line 1801, in read_tabular_manifest
    yield from _read_tabular_manifest_rows(
  File "spinta/manifests/tabular/helpers.py", line 1756, in _read_tabular_manifest_rows
    yield from state.release(reader)
  File "spinta/manifests/tabular/helpers.py", line 1718, in release
    parent.leave()
  File "spinta/manifests/tabular/helpers.py", line 1276, in leave
    self.state.stack[-1].append(self.data)
  File "spinta/manifests/tabular/helpers.py", line 1439, in append
    self._get_and_append_data(node.data['params'][self.name], row)
KeyError: 'param2'
```

## Resource

- https://ivpk.github.io/dsa/dimensijos.html#param

## Solution

Skaitymo metu renkant duomenis is keliu eiliuciu nebuvo pradinio rakta kur deti kitus ref irasus (asmuo, tipas, kodas).

Sprendimas sukuriant pradini zodyno rakta duomenu surinkimui - https://github.com/atviriduomenys/spinta/pull/1110. Po jo deja gaunama kita klaida:

```python
Traceback (most recent call last):
  File "spinta/cli/config.py", line 38, in check
    prepare_manifest(context, ensure_config_dir=True, full_load=True)
  File "spinta/cli/helpers/store.py", line 147, in prepare_manifest
    store = load_manifest(
  File "spinta/cli/helpers/store.py", line 129, in load_manifest
    commands.load(
  File "spinta/manifests/yaml/commands/load.py", line 110, in load
    commands.load(
  File "spinta/manifests/tabular/commands/load.py", line 59, in load
    load_manifest_nodes(context, into, schemas, source=manifest)
  File "spinta/manifests/helpers.py", line 137, in load_manifest_nodes
    node = _load_manifest_node(context, config, manifest, source, eid, schema)
  File "spinta/manifests/helpers.py", line 203, in _load_manifest_node
    commands.load(context, node, data, manifest, source=source)
  File "spinta/types/model.py", line 144, in load
    commands.load(context, model.external, external, manifest)
  File "spinta/datasets/commands/load.py", line 128, in load
    _check_unknown_keys(entity.model, pkeys, entity.model.properties)
  File "spinta/datasets/commands/load.py", line 116, in _check_unknown_keys
    raise MultipleErrors(
spinta.exceptions.MultipleErrors: Multiple errors:
 - Property 'address.id' not found.
     Context:
       component: spinta.components.Model
       manifest: default
       schema: Sheet1:13
       model: Address
       entity: None
       property: address.id
```

tačiau panašu, kad tai nesusiję su šia problema ir bus išspręsta su https://github.com/atviriduomenys/spinta/issues/981#issuecomment-2615790528

**Comment by ievabraskute** [comment]
```python
Exception has occurred: KeyError       (note: full exception trace is shown but execution is paused at: load)
'list_type'
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 1343, in append
    self._get_and_append_data(node.data['params'][self.name], row)
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 1180, in leave
    self.state.stack[-1].append(self.data)
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 1624, in release
    parent.leave()
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 1662, in _read_tabular_manifest_rows
    yield from state.release(reader)
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 1707, in read_tabular_manifest
    yield from _read_tabular_manifest_rows(
  File "/Users/ibraske/projects/spinta/spinta/manifests/helpers.py", line 133, in load_manifest_nodes
    for eid, schema in schemas:
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/commands/load.py", line 59, in load (Current frame)
    load_manifest_nodes(context, into, schemas, source=manifest)
  File "/Users/ibraske/projects/spinta/spinta/manifests/yaml/commands/load.py", line 110, in load
    commands.load(
  File "/Users/ibraske/projects/spinta/spinta/cli/helpers/store.py", line 127, in load_manifest
    commands.load(
  File "/Users/ibraske/projects/spinta/spinta/cli/manifest.py", line 176, in _read_and_return_rows
    store = load_manifest(
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 2667, in <genexpr>
    rows = ({c: row[c] for c in cols} for row in rows)
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 2684, in write_csv
    writer.writerows(rows)
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 2669, in write_tabular_manifest
    write_csv(pathlib.Path(path), rows, cols)
  File "/Users/ibraske/projects/spinta/spinta/cli/manifest.py", line 133, in copy_manifest
    write_tabular_manifest(context, output, rows)
  File "/Users/ibraske/projects/spinta/spinta/cli/manifest.py", line 62, in copy
    copy_manifest(
  File "/Users/ibraske/projects/spinta/_process_dsa.py", line 50, in main
    result = runner.invoke(app, args)
  File "/Users/ibraske/projects/spinta/_process_dsa.py", line 61, in <module>
    main()
KeyError: 'list_type'
```

**Comment by varzgalys** [comment]
Cant access the input file.

**Comment by karina-klinkeviciute** [comment]
failas įkeltas į sutartą direktoriją Teams

**Comment by karina-klinkeviciute** [comment]
[pavyzdys_979.xlsx](https://github.com/user-attachments/files/18563334/pavyzdys_979.xlsx)

šiame faile yra keli parametrai, kaip ir faile, su kuriuo gauta klaida. 

Paleidus `spinta check pavyzdys_979.xlsx` gaunu tokią klaidą: `KeyError: 'param2'`

Jos neturėtų būti, patikrinimas turėtų praeiti be klaidų.

**Comment by sirex** [comment]
Užduoties aprašymas neatitinka

https://spinta.readthedocs.io/en/latest/contrib/issues.html#task-description

Nėra minimalaus atkartojamo pavyzdžio, su įvesties ir išvesties  failais ir klaidos traceback.

**Comment by karina-klinkeviciute** [comment]
atnaujinau aprašymą

**Comment by varzgalys** [comment]
@karina-klinkeviciute Patikslink prašau ar `copy` komandos šiam DSA:

```
d | r | b | m | property  | type    | ref    | source      | prepare
test_dataset              |         |        |             |
  | resource1             | xml     |        |             |
                          | param   | param1 | param1      | body()
                          |         | param2 | param2      | body()
                          |         | param3 | param3      | body()
                          |         |        |             |
  |   |   | Continent     |         |        |             |
  |   |   |   | name      | string  |        | name/text() |
  |   |   |   | id        | integer |        | name/text() |
```


tikrai turi buti toks pat? Nes kolkas gaunamas toks output:

```
id | d | r | b | m | property  | type    | ref    | source      | prepare | level | access | uri | title | description
   | test_dataset              |         |        |             |         |       |        |     |       |
   |   | resource1             | xml     |        |             |         |       |        |     |       |
   |                           | param   | param1 | param1      | body()  |       |        |     |       |
   |                           | param   | param2 | param2      | body()  |       |        |     |       |
   |                           | param   | param3 | param2      | body()  |       |        |     |       |
   |                           |         |        |             |         |       |        |     |       |
   |   |   |   | Continent     |         |        |             |         |       |        |     |       |
   |   |   |   |   | name      | string  |        | name/text() |         |       |        |     |       |
   |   |   |   |   | id        | integer |        | name/text() |         |       |        |     |       |
```

Kas remiantis šiuo jau egzistuojančiu testu - https://github.com/atviriduomenys/spinta/blob/ddcc5ebfa202c562d93f26bf46e29b49850e5591/tests/manifests/test_manifest.py#L692
atrodo teisingas ir labiau neteisingas input DSA? Dokumentacijoje nelabai randam informacijos apie šia dalį (keli param resursui)

**Comment by karina-klinkeviciute** [comment]
Pagal dokumentaciją, `param` galima nurodyti ir tik prie vieno parametro, o kiti žemiau einantys tada irgi turi būti suprantami, kaip parametrai: https://ivpk.github.io/dsa/draft/dimensijos.html#param - čia žemiau yra pavyzdžių. 

Turbūt galima `param` prirašyti ir prie kiekvieno parametro, bet pagal dokumentaciją, `param` užtenka nurodyti vieną kartą. 

Dėl to, ar rezultatas turi gauti identiškas, ar gali būti, kad rezultatas kažkiek skiriasi, jei abu yra tinkami, tai net nežinau. Iš varotojo pusės žiūrint, jei aš pildyčiau DSA, tai paleidus `spinta copy` (pavyzdžiui, kai kopijuojama iš xlsx į csv, ar iš ŠDSA su šaltinio duomenimis į DSA be šaltinio duomenų) tikėčiausi, kad rezultatas būtų toks pats, kaip pateikiau, ir taip pat, kad atitiktų dokumentaciją. 

Bet kadangi Product Owner yra Mantas, turbūt reikėtų klausti jo, ar toks rezultatas, koks gaunamas dabar, yra tinkamas.
