### ISSUE TITLE
`spinta check` nepalaikomi daliniai modeliai (su `/:part`)

### ISSUE THREAD

**Issue by karina-klinkeviciute** [atviriduomenys/spinta#997]
Kol kas nepalaikomi daliniai modeliai, t.y. tokie modeliai, kurie negali būti pasiekiami patys, o duomenis gali teikti. Jie žymimi priedu `/:part`

DSA pavyzdys:
```
        d | r | b | m | property   | type         | ref     | access | title
        example                    |              |         |        |
                                   |              |         |        |
          |   |   | City/:part     |              |         |        |
          |   |   |   | id         | integer      |         | open   |
          |   |   |   | name       | integer      |         | open   |
          |   |   |   | country    | ref required | Country | open   |
                                   |              |         |        |
          |   |   | Country        |              |         |        |
          |   |   |   | id         | integer      |         | open   |
          |   |   |   | name       | string       |         | open   |
          |   |   |   | cities[]   | backref      | City    | open   |
```
Leidžiant `spinta check`, kyla klaida: 

Traceback (most recent call last):
  File "/home/karina/work/vssa/spinta/venv310/bin/spinta", line 8, in <module>
    sys.exit(app())
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/typer/main.py", line 341, in __call__
    raise e
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/typer/main.py", line 324, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/typer/core.py", line 757, in main
    return _main(
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/typer/core.py", line 195, in _main
    rv = self.invoke(ctx)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/typer/main.py", line 699, in wrapper
    return callback(**use_params)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/spinta/cli/config.py", line 38, in check
    prepare_manifest(context, ensure_config_dir=True, full_load=True)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/spinta/cli/helpers/store.py", line 147, in prepare_manifest
    store = load_manifest(
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/spinta/cli/helpers/store.py", line 135, in load_manifest
    commands.link(context, store.manifest)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 279, in __call__
    return func(*args, **kwargs)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/spinta/manifests/commands/link.py", line 11, in link
    commands.link(context, obj)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 279, in __call__
    return func(*args, **kwargs)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/spinta/types/model.py", line 232, in link
    commands.link(context, prop)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 279, in __call__
    return func(*args, **kwargs)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/spinta/types/model.py", line 381, in link
    commands.link(context, prop.dtype)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 279, in __call__
    return func(*args, **kwargs)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/spinta/types/array/link.py", line 92, in link
    commands.link(context, dtype.items.dtype)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/multipledispatch/dispatcher.py", line 279, in __call__
    return func(*args, **kwargs)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/spinta/types/backref/link.py", line 93, in link
    _link_backref(context, dtype)
  File "/home/karina/work/vssa/spinta/venv310/lib/python3.10/site-packages/spinta/types/backref/link.py", line 70, in _link_backref
    raise ModelReferenceNotFound(dtype, ref=backref_target_model)
spinta.exceptions.ModelReferenceNotFound: Model reference 'example/City' not found.
  Context:
    component: spinta.types.datatype.BackRef
    manifest: default
    schema: 9
    dataset: example
    model: example/Country
    entity: 
    property: cities
    attribute: 
    type: backref
    ref: example/City

Pageidaujamas rezultatas:

leidžiant `spinta check`, turėtų būti rašoma "OK", klaida neturėtų būti rodoma. 

### Susiję

- https://github.com/atviriduomenys/spinta/issues/927

**Comment by ievabraskute** [comment]
Related:



![Image](https://github.com/user-attachments/assets/36662395-802e-4f0e-b450-699352d8d485)

```python
Property 'code' not found.
  Context:
    component: spinta.components.Model
    manifest: default
    schema: Sheet1:78
    model: LicenceLegalEntityForeign
    entity: None
    property: code
  File "/Users/ibraske/projects/spinta/spinta/types/model.py", line 123, in load (Current frame)
    raise PropertyNotFound(model, property=prop_name)
  File "/Users/ibraske/projects/spinta/spinta/manifests/helpers.py", line 203, in _load_manifest_node
    commands.load(context, node, data, manifest, source=source)
  File "/Users/ibraske/projects/spinta/spinta/manifests/helpers.py", line 137, in load_manifest_nodes
    node = _load_manifest_node(context, config, manifest, source, eid, schema)
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/commands/load.py", line 59, in load
    load_manifest_nodes(context, into, schemas, source=manifest)
  File "/Users/ibraske/projects/spinta/spinta/manifests/yaml/commands/load.py", line 110, in load
    commands.load(
  File "/Users/ibraske/projects/spinta/spinta/cli/helpers/store.py", line 127, in load_manifest
    commands.load(
  File "/Users/ibraske/projects/spinta/spinta/cli/manifest.py", line 176, in _read_and_return_rows
    store = load_manifest(
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 2667, in <genexpr>
    rows = ({c: row[c] for c in cols} for row in rows)
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 2684, in write_csv
    writer.writerows(rows)
  File "/Users/ibraske/projects/spinta/spinta/manifests/tabular/helpers.py", line 2669, in write_tabular_manifest
    write_csv(pathlib.Path(path), rows, cols)
  File "/Users/ibraske/projects/spinta/spinta/cli/manifest.py", line 133, in copy_manifest
    write_tabular_manifest(context, output, rows)
  File "/Users/ibraske/projects/spinta/spinta/cli/manifest.py", line 62, in copy
    copy_manifest(
  File "/Users/ibraske/projects/spinta/_process_dsa.py", line 52, in main
    result = runner.invoke(app, args)
  File "/Users/ibraske/projects/spinta/_process_dsa.py", line 63, in <module>
    main()
spinta.exceptions.PropertyNotFound: Property 'code' not found.
  Context:
    component: spinta.components.Model
    manifest: default
    schema: Sheet1:78
    model: LicenceLegalEntityForeign
    entity: None
    property: code

```

**Comment by sirex** [comment]
Change current internal data model by adding:

```python
class Model:
  features: dict[str, PartialModel]

class PartialModel(Model):
  model: Model  # parent model
  params: UlrParams  # From `City/:part` would be `params.part`
```
